replicaCount: 3

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts: 
    - adform-bloom.app.pp.adform.zone
  tls:
    - hosts: [adform-bloom.app.pp.adform.zone]

resources:
 limits:
   cpu: 800m
   memory: 2Gi
 requests:
   cpu: 500m
   memory: 1Gi
    
autoscaler:
  enabled: true
  maxReplicaCount: 5
  targetAverageUtilization: 60

environment:
  ASPNETCORE_ENVIRONMENT: pp