replicaCount: 3

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - adform-bloom-runtime.app.pr.adform.zone
  tls:
    - hosts: [adform-bloom-runtime.app.pr.adform.zone]

resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 2500m
    memory: 3Gi

autoscaler:
  enabled: false
  maxReplicaCount: 3
  targetAverageUtilization: 60

environment:
  ASPNETCORE_ENVIRONMENT: pr
