tenant: "Scope CIAM"

replicaCount: 2

containerPort: 80

service:
  port: 80

additionalPorts: 
 - name: grpc
   containerPort: 9696
   servicePort: 9696
   protocol: TCP

image:
  repository: docker.artifactory.adform.com/ciam/adform-bloom-read

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 5
    successThreshold: 1
    timeoutSeconds: 1
    url: /healthy
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 10
    successThreshold: 1
    timeoutSeconds: 2
    url: /ready

maas:
  enabled: true
  labels:
    service: 'adform-bloom-read'

laas:
  enabled: true
  format: "json"

secrets:
  enabled: true
  patch: true

resources:
 limits:
   cpu: 400m
   memory: 2Gi
 requests:
   cpu: 200m
   memory: 1Gi
